# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

array_ten = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

array_ten.each do |array|
  if (array_ten[-2] + array_ten[-1] < 4_000_000)
    array_ten << (array_ten[-2] + array_ten[-1])
  end
  array_ten
end

sum = 0
array_ten.each do |number|
  sum+=number if (number%2==0)
  sum
end

puts sum
